### ISSUE TITLE
Сбивается подсветка кода в ответах

### ISSUE THREAD

**Issue by padlyuck** [yarkovaleksei/toster-tools#15]
При автоматическом обновлении ответов на странице вопроса сбивается подсветка кода. 
Для примера открываем страницу https://toster.ru/q/414294 ждем указанное в настройках расширения время и наблюдаем код еще с форматированием, но уже без подсветки. 
Не проверял, но вероятнее всего в комментариях к ответу ситуация такая же.

**Comment by yarkovaleksei** [comment]
Спасибо за отзыв. Баг известен мне, но пока не могу понять где инициализируется подсветка кода.
