### ISSUE TITLE
Вылетает расширение

### ISSUE THREAD

**Issue by padlyuck** [yarkovaleksei/toster-tools#16]
Периодически(где-то раз в день) хром выдает сообщение о том, что расширение вылетело и предлагает его(расширение) перезагрузить. Больше информации дать не могу, т.к. не знаю где её взять. Если подскажите где смотреть подробности вылета - смогу прислать больше подробностей.

**Comment by yarkovaleksei** [comment]
Память течет :disappointed:
Я уже всю голову сломал. Вылетает видимо из-за того, что превышен лимит памяти.
Спасибо за отзыв.
