### ISSUE TITLE
В popup расширения Chrome не отображаются иконки

### ISSUE THREAD

**Issue by arhangelsoft** [yarkovaleksei/toster-tools#17]
Ну собственно вот:
![](http://ipic.su/img/img7/fs/screenshot2017-04-29001.1493453232.png)

**Comment by yarkovaleksei** [comment]
Какая ОС? Баг повторяется или был один раз?
Непонятно что могло привести к этому, так как иконки зашиты в архив с расширением, а не подгружаются из сторонних источников.

**Comment by arhangelsoft** [comment]
ОС: Windows Server 2003, хром 49-й версии.
Баг есть даже на текущей v3.36.18 версии.
Картинки ищет по этому пути:
`chrome-extension://kpfolongmglpleidinnhnlefeoljdecm/icon/svg/github.svg`

Если открыть этот путь в браузере - картинка есть. 
Проверял в более новой версии хрома - проблемы нет.
Может баг самого хрома?

**Comment by yarkovaleksei** [comment]
Попробуйте в режиме разработчика установить. Баг скорее всего в Хроме.

**Comment by arhangelsoft** [comment]
Баг старого браузера.
