### ISSUE TITLE
Отображение/уведомление о вопросах по конкретным тегам

### ISSUE THREAD

**Issue by arhangelsoft** [yarkovaleksei/toster-tools#18]
Хотелось бы на самой иконке badge'м другого цвета отображать вопросы по конкретным интересующим меня тегам, из моего feed'а. Например я подписан на C++, C#, F#, но вот получать вопросы и отвечать мне интересно только по C#.

**Comment by yarkovaleksei** [comment]
Это трудновыполнимая задача. На данный момент Тостер не предлагает API для разработчиков и расширение тупо парсит HTML для отображения результата.
Заявленная вами фича добавлена в ближайшее время не будет.
