### ISSUE TITLE
Скрытие правой панели ломает вёрстку

### ISSUE THREAD

**Issue by arhangelsoft** [yarkovaleksei/toster-tools#19]
Собственно вот:
![](http://ipic.su/img/img7/fs/screenshot2017-04-29001.1493466914.png)

**Comment by yarkovaleksei** [comment]
Мало информации. Какой браузер? ОС? Проверял на Ubuntu и Windows в Chrome, FF и Opera (все последних версий).
У меня все ОК. Я этот момент учел еще тогда, когда добавлял фичу. Отступы выставляются корректно.
Попробуйте воспроизвести баг и отпишитесь, пожалуйста.

**Comment by arhangelsoft** [comment]
Баг старого браузера.
