### ISSUE TITLE
Моноширинный шрифт для кода в вопросах/ответах

### ISSUE THREAD

**Issue by delphinpro** [yarkovaleksei/toster-tools#23]
Спасибо за реализацию запрошенной фичи для отображения ввода моноширинным шрифтом.
Теперь хочется большего - такую же опцию для всего кода на сайте.
Я подсел на лигатурные шрифты, хочу видеть их везде =)
Вот пример http://s.delphinpro.ru/20170602-184559.png
В окне редактирования лигатуры работают, а в отправленном ответе - нет, там тостер использует Consolas. вот эту фигню хотелось бы и заменить. Прямо весь стек для code/pre на простое значение  "monospace".

**Comment by yarkovaleksei** [comment]
Спасибо за отклик. Да, конечно, добавлю такую возможность в ближайший свой выходной.

**Comment by delphinpro** [comment]
Огромное спасибо! Какая красота http://s.delphinpro.ru/20170604-190106.png =)

**Comment by yarkovaleksei** [comment]
Не за что :smiley:
