### ISSUE TITLE
Badge-уведомления. Отображение разными цветами различных типов уведомлений, фильтр уведомлений. 

### ISSUE THREAD

**Issue by arhangelsoft** [yarkovaleksei/toster-tools#24]
Добрый день,

такая мысль:
В зависимости от имеющихся не прочитанных уведомлений красить badge в цвет уведомления:
Кому-то нравится - красный фон
Комментарий - фиолетовый
Пригласили экспертом - желтый
Решение - зеленый

если имеется несколько типов сразу, то происходит ротация с изменением цвета и кол-ва уведомлений по типам.

**Comment by yarkovaleksei** [comment]
@arhangelsoft Не совсем понятно что именно вы хотите. Вынести цвет бэйджа в настройки не проблема. Проблема в том, что у Тостера нет API и приходится парсить HTML, чтоб выбрать результаты. И как менять цвет в зависимости от типа уведомления я не знаю.
Может что-то подскажете?

**Comment by arhangelsoft** [comment]
@yarkovaleksei сейчас бэйдж отображает общее количество уведомлений на красном фоне.

Когда есть комментарии, цвет бэйджа меняется на фиолетовый с отображением кол-ва только комментариев.
и так далее для прочих типов уведомлений:
Комментарий - фиолетовый + кол-во комментириев
Пригласили экспертом - желтый + число приглашений
Решение - зеленый + число решений

> Проблема в том, что у Тостера нет API и приходится парсить HTML, чтоб выбрать результаты. 

да, это проблема. Уже сам посмотрел, нужно перебрать всю страницу уведомлений и выгрести оттуда не просмотренные, это геморой.
